# Settings for the MQTT Client. Currently only these three are supported
mqtt:

  # Change au1.cloud.thethings.network to our MQTT Public Address
  server: tcp://localhost:1883

  # Change luppy-application@ttn to our MQTT Username
  user:

  # Change YOUR_API_KEY to our MQTT Password
  password:

  # Topic path to subscribe to. "#" means All Topics.
  topic_path: "application/+/device/+/event/up"

  # MQTT QoS level
  qos: 0

  # Extract the device ID (eui-YOUR_DEVICE_EUI) from the topic path, which looks like...
  # v3/luppy-application@ttn/devices/eui-YOUR_DEVICE_EUI/up
  device_id_regex: "(.*/)?(?P<deviceid>.*)/event/up"

  # Optional: for TLS client certificates
  # ca_cert: certs/AmazonRootCA1.pem
  # client_cert: certs/xxxxx-certificate.pem.crt
  # client_key: certs/xxxxx-private.pem.key

  # Optional: Used to specify ClientID. The default is <hostname>-<pid>
  # client_id: somedevice

cache:

  # Timeout. Each received metric will be presented for this time if no update is send via MQTT.
  # Set the timeout to -1 to disable the deletion of metrics from the cache. The exporter presents the ingest timestamp
  # to prometheus.
  timeout: 24h

# List of valid metrics. Only metrics listed here will be exported
metrics:

  # Temperature Metric
  # Name of the metric in prometheus
  - prom_name: room
    # Name of the metric in a MQTT JSON message
    mqtt_name: "tags.room"
    # Prometheus help text for this metric
    help: "Room"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: room

  # Temperature Metric
  # Name of the metric in prometheus
  - prom_name: temperature
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.temperature"
    # Prometheus help text for this metric
    help: "Temperature"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: temperature

  # Temperature Metric
  # Name of the metric in prometheus
  - prom_name: humidity
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.humidity"
    # Prometheus help text for this metric
    help: "Humidity"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: humidity

  # Light Level Metric
  # Name of the metric in prometheus
  - prom_name: light
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.light"
    # Prometheus help text for this metric
    help: "Light Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: light

  # illumination Level Metric
  # Name of the metric in prometheus
  - prom_name: illumination
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.illumination"
    # Prometheus help text for this metric
    help: "Illumination Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: illumination

  # co2 Level Metric
  # Name of the metric in prometheus
  - prom_name: co2
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.co2"
    # Prometheus help text for this metric
    help: "Co2 Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: co2

  # pressure Level Metric
  # Name of the metric in prometheus
  - prom_name: pressure
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.pressure"
    # Prometheus help text for this metric
    help: "Pressure Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: pressure

  # tvoc Level Metric
  # Name of the metric in prometheus
  - prom_name: tvoc
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.tvoc"
    # Prometheus help text for this metric
    help: "Tvoc Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: tvoc

  # infrared Level Metric
  # Name of the metric in prometheus
  - prom_name: infrared
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.infrared"
    # Prometheus help text for this metric
    help: "Infrared Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: infrared

  # Activity Level Metric
  # Name of the metric in prometheus
  - prom_name: activity
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.activity"
    # Prometheus help text for this metric
    help: "Activity Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: activity

  # pressure Level Metric
  # Name of the metric in prometheus
  - prom_name: pm2_5
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.pm2_5"
    # Prometheus help text for this metric
    help: "PM 2.5 Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: pm2_5

  # tvoc Level Metric
  # Name of the metric in prometheus
  - prom_name: pm10
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.pm10"
    # Prometheus help text for this metric
    help: "PM10 Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: pm10

  # hcho Level Metric
  # Name of the metric in prometheus
  - prom_name: hcho
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.hcho"
    # Prometheus help text for this metric
    help: "HCHO Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: hcho

  # Light Level 2  Metric
  # Name of the metric in prometheus
  - prom_name: light_level
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.light_level"
    # Prometheus help text for this metric
    help: "Light Level"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: light_level

  # Battery Level  Metric
  # Name of the metric in prometheus
  - prom_name: battery
    # Name of the metric in a MQTT JSON message
    mqtt_name: "object.battery"
    # Prometheus help text for this metric
    help: "Battery"
    # Prometheus type for this metric. Valid values are: "gauge" and "counter"
    type: gauge
    # Map of string to string for constant labels. This labels will be attached to every prometheus metric
    const_labels:
      sensor_type: battery_level
